### PR TITLE
Clean up spacing in README example

### PR DESCRIPTION
**Pull request by captbaritone**

### CODE REVIEW

**Comment by platinumazure** [comment]
Would you mind prepending the commit message with "Docs:"? Otherwise LGTM.

**Comment by captbaritone** [comment]
Updated

**Comment by platinumazure** [comment]
Thanks! Can't believe I didn't notice it.

**Comment by captbaritone** [comment]
If only there was some kind of linter for markdown... ;)

## 

Jordan Eldredge

Please excuse any typos or terseness; this email was sent from a mobile device.

**Comment by platinumazure** [comment]
I'll get to that... Feel free to open an issue if you like.

**Comment by captbaritone** [comment]
I intended that to be sarcastic. But now you got me thinking… ;-)

## 

Jordan Eldredge

Please excuse any typos or terseness; this email was sent from a mobile device.

**Comment by platinumazure** [comment]
Oh, I thought you were referring to eslint-plugin-markdown. I don't know if
that handles JSON, though.

**Comment by captbaritone** [comment]
In this case the actual error was mixing tabs (which I'm guessing you have set to eight spaces?) with spaces. So a linter would not actually have to understand JSON to help.

All that aside, linting the README is probably the distraction of dubious value ;-)

**Pull request merged**
